version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: visualmecanica-frontend-prod
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.prod
    container_name: visualmecanica-backend-prod
    ports:
      - "8080:80"
    env_file:
      - ./Backend/.env.production
    depends_on:
      - database
    volumes:
      - ./Backend:/var/www/html
      - ./Backend/logs:/var/log/php
    restart: always

  database:
    image: mysql:8.0
    container_name: visualmecanica-database-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: